# Generated by Django 3.0.7 on 2020-06-16 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crusts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeof_crust', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Flavors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeof_flavor', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeof_size', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pizza_crust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas_crust', to='orders.Crusts')),
                ('pizza_flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas_flavor', to='orders.Flavors')),
                ('pizza_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas_size', to='orders.Sizes')),
            ],
        ),
    ]
