# Generated by Django 3.0.7 on 2020-06-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeof_extra1', models.CharField(max_length=64, null=True)),
                ('typeof_extra2', models.CharField(max_length=64, null=True)),
                ('typeof_extra3', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pizzas',
            name='pizza_extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizzas_extra', to='orders.Extras'),
        ),
    ]
