# Generated by Django 3.0.7 on 2020-06-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200616_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extras',
            old_name='typeof_extra1',
            new_name='typeof_extra',
        ),
        migrations.RemoveField(
            model_name='extras',
            name='typeof_extra2',
        ),
        migrations.RemoveField(
            model_name='extras',
            name='typeof_extra3',
        ),
    ]
