# Generated by Django 3.0.7 on 2020-06-16 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200616_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='typeof_extra',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='pizza_extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas_extra', to='orders.Extras'),
        ),
    ]
