# Generated by Django 3.0.7 on 2020-06-16 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200616_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzas',
            name='pizza_extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizzas_extra', to='orders.Extras'),
        ),
    ]
