# Generated by Django 3.0.7 on 2020-06-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200616_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeof_crust', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeof_extra', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeof_flavor', models.CharField(max_length=64)),
                ('decriptionof_flavor', models.TextField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pizza_crust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas_crust', to='orders.Crust')),
                ('pizza_flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas_flavor', to='orders.Flavor')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeof_size', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='extras',
            name='pizzas_extra',
        ),
        migrations.RemoveField(
            model_name='pizzas',
            name='pizza_crust',
        ),
        migrations.RemoveField(
            model_name='pizzas',
            name='pizza_flavor',
        ),
        migrations.RemoveField(
            model_name='pizzas',
            name='pizza_size',
        ),
        migrations.DeleteModel(
            name='Crusts',
        ),
        migrations.DeleteModel(
            name='Extras',
        ),
        migrations.DeleteModel(
            name='Flavors',
        ),
        migrations.DeleteModel(
            name='Pizzas',
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas_size', to='orders.Size'),
        ),
        migrations.AddField(
            model_name='extra',
            name='pizzas_extra',
            field=models.ManyToManyField(blank=True, related_name='pizzas_extra', to='orders.Pizza'),
        ),
    ]
