# Generated by Django 3.0.7 on 2020-06-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200616_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavors',
            name='decriptionof_flavor',
            field=models.TextField(default='', max_length=512),
        ),
    ]
