# Generated by Django 3.0.7 on 2020-06-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200617_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='pizzas_extra',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizzas_extra',
            field=models.ManyToManyField(related_name='pizzas_extras', to='orders.Extra'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='typeof_extra',
            field=models.CharField(max_length=64),
        ),
    ]
