# Generated by Django 3.0.7 on 2020-06-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200618_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='username',
            field=models.CharField(default='', max_length=64),
        ),
    ]
