# Generated by Django 3.0.7 on 2020-06-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_pizza_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='total_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
