# Generated by Django 3.0.7 on 2020-06-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_pizza_total_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='quantity',
        ),
    ]
