# Generated by Django 3.0.7 on 2020-06-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='steps',
            field=models.CharField(choices=[('1', 'Buon Appetito!'), ('2', 'In delivery'), ('3', 'We are preparing your order'), ('4', 'We are cooking your pizza'), ('5', 'We have received your order')], max_length=256),
        ),
    ]
