# Generated by Django 3.0.7 on 2020-06-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200622_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
