# Generated by Django 3.0.7 on 2020-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_delete_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='progress',
            field=models.CharField(choices=[('1', 'Buon Appetito!'), ('2', 'In delivery'), ('3', 'We are preparing your order'), ('4', 'We are cooking your pizza'), ('5', 'We have received your order')], default='', max_length=256),
        ),
    ]
