# Generated by Django 3.0.7 on 2020-06-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200622_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='progress',
            field=models.CharField(choices=[('Buon Appetito!', 'Buon Appetito!'), ('In delivery', 'In delivery'), ('We are preparing your order', 'We are preparing your order'), ('We are cooking your pizza', 'We are cooking your pizza'), ('We have received your order', 'We have received your order')], default='', max_length=256),
        ),
    ]
