# Generated by Django 3.0.7 on 2020-06-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20200622_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flavor',
            old_name='decriptionof_flavor',
            new_name='description',
        ),
    ]
