# Generated by Django 3.0.7 on 2020-06-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20200622_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='city_zip',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='pizza',
            name='number_floor',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='pizza',
            name='province',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='pizza',
            name='street',
            field=models.CharField(default='', max_length=256),
        ),
    ]
