# Generated by Django 3.0.7 on 2020-06-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20200623_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='comments',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='pizza',
            name='payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default='', max_length=256),
        ),
    ]
